### ISSUE TITLE
[BUG] copy-components doesn't work

### ISSUE THREAD

**Issue by davidrhoderick** [vuestorefront/storefront-ui#1810]
**Describe the bug**
`yarn copy-components` and `npm copy-components` do not work as expected.

**How to reproduce**
1. Read the documentation [here](https://docs.storefrontui.io/?path=/docs/setup-pull-off-components--page).
2. Navigate from the root project directory to `/node_modules/@storefront-ui/vue/`.
3. Run `yarn copy-components` or `npm copy-components`.

**Expected behavior**
I expect to see the components copied for editing/examination.

**Actual behavior**
I get the following errors

**Code run + error log**
After running `yarn copy-components`, I get the following:
```
yarn copy-components
yarn run v1.22.10
$ node scripts/copy-components.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'fse'
Require stack:
- /home/username/Development/company/store-front/node_modules/@storefront-ui/vue/scripts/copy-components.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/username/Development/company/store-front/node_modules/@storefront-ui/vue/scripts/copy-components.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/username/Development/company/store-front/node_modules/@storefront-ui/vue/scripts/copy-components.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Or from `npm copy-components`:
```
npm copy-components

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /home/username/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.14.12 /home/username/n/lib/node_modules/npm
```

**Additional context**
Not sure I can show the entire repository or not but I can include various other files.  For example, here is my root directory's `package.json`:
```
{
  "name": "ecommerce-integration-boilerplate",
  "private": true,
  "license": "MIT",
  "engines": {
    "node": ">=10.x"
  },
  "scripts": {
    "build": "yarn build:api-client && yarn build:composables && yarn build:theme",
    "build:api-client": "cd packages/api-client && yarn build",
    "build:composables": "cd packages/composables && yarn build",
    "build:theme": "cd packages/theme && yarn build",
    "dev": "concurrently \"yarn:dev:*\"",
    "dev:api-client": "cd packages/api-client && yarn dev",
    "dev:composables": "cd packages/composables && yarn dev",
    "dev:theme": "cd packages/theme && yarn dev",
    "test": "yarn test:api-client && yarn test:composables && yarn test:theme",
    "test:api-client": "cd packages/api-client && yarn test --passWithNoTests",
    "test:composables": "cd packages/composables && yarn test --passWithNoTests",
    "test:theme": "cd packages/theme && yarn test --passWithNoTests",
    "lint": "eslint . --ext .ts,.vue",
    "start": "cd packages/theme && yarn start"
  },
  "devDependencies": {
    "@babel/core": "^7.10.5",
    "@types/jest": "^24.0.23",
    "@types/node": "^12.12.14",
    "@typescript-eslint/eslint-plugin": "^4.4.0",
    "@typescript-eslint/parser": "^4.4.0",
    "@vue-storefront/core": "^2.2.2",
    "@vue/eslint-config-typescript": "^7.0.0",
    "concurrently": "^5.3.0",
    "eslint": "7.10.0",
    "eslint-config-standard": "^14.1.0",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-node": "^11.0.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "eslint-plugin-vue": "^7.0.1",
    "husky": "^4.2.3",
    "jest": "^24.9.0",
    "lerna": "^3.15.0",
    "lint-staged": "^10.0.7",
    "rimraf": "^3.0.2",
    "rollup": "^1.25.2",
    "rollup-plugin-typescript2": "^0.29.0",
    "ts-jest": "^26.4.3",
    "ts-node": "^8.4.1",
    "tslib": "^2.0.3",
    "typescript": "~4.1",
    "vue-eslint-parser": "^7.0.0"
  },
  "workspaces": [
    "packages/*"
  ],
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.{js,ts,vue}": "eslint --fix"
  }
}
```
Here's the theme's `package.json`:
```
{
  "name": "@company/store-front-theme",
  "version": "0.0.3",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build -m",
    "build:analyze": "nuxt build -a -m",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "test": "jest"
  },
  "dependencies": {
    "@storefront-ui/vue": "^0.9.1",
    "@company/store-front": "0.0.1",
    "@vue-storefront/nuxt": "^2.2.1",
    "@vue-storefront/nuxt-theme": "^2.2.1",
    "@nuxtjs/style-resources": "^1.0.0",
    "cookie-universal-nuxt": "^2.1.3",
    "core-js": "^2.6.5",
    "nuxt": "^2.13.3",
    "nuxt-i18n": "^6.5.0",
    "vee-validate": "^3.2.3",
    "vue-scrollto": "^2.17.1"
  },
  "devDependencies": {
    "@nuxt/types": "^0.7.9",
    "@nuxt/typescript-build": "^2.0.0",
    "@vue/test-utils": "^1.0.0-beta.27",
    "babel-jest": "^24.1.0",
    "jest": "^24.1.0",
    "vue-jest": "^4.0.0-0"
  }
}
```

The project is working otherwise.  Let me know if there is anything I should do to "reset" the project and try again because I'm a bit new to Vue Storefront.

**Comment by justyna-13** [comment]
Hi @davidrhoderick I think you missed a requred part from our [docs](https://docs.storefrontui.io/?path=/docs/setup-pull-off-components--page): 
"`fse` package added to your project with npm install `fse -D` or `yarn add fse -D`". Without this package you can't copy components to your project :slightly_smiling_face:

**Comment by davidrhoderick** [comment]
Yep, that's exactly right, can't believe I missed it.  Sorry for the bug reporting and thanks for gently pointing out my mistake!
