### ISSUE TITLE
[BUG] missing glob dependency

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront/storefront-ui#1923]
**Describe the bug**

Added a missing dependency causing Error: @storefront-ui/vue tried to access glob, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound. when using yarn2

Issue by @samriley

**Comment by AdamPawlinski** [comment]
I made tests using 0.10.8 SFUI version on VSF Next project and on clear project with SFUI and didn't find any error connected with glob dependency. Please clarify how to reproduce this bug so we can check it or we can close this issue.

**Comment by samriley** [comment]
not sure if you saw my comment in the pr - https://github.com/vuestorefront/storefront-ui/pull/1793#issuecomment-886039360

im just starting with a fresh yarn2 based project and adding the @storefront-ui/vue dependency

during the install i see

```YN0009: │ @storefront-ui/vue@npm:0.10.71 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/rb/_gfw04rx6cx8wy3mkx37qlch0000gp/T/xfs-dcf214bf/build.log)```

the contents of that file include

```# This file contains the result of Yarn building a package (@storefront-ui/vue@npm:0.10.71)
# Script name: postinstall

/Users/sam/dev/test-storefront-ui/.pnp.js:8198
    throw firstError;
    ^

Error: @storefront-ui/vue tried to access glob, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: glob (via "glob")
Required by: @storefront-ui/vue@npm:0.10.71 (via /Users/sam/dev/test-storefront-ui/.yarn/unplugged/@storefront-ui-vue-npm-0.10.71-d47225d01b/node_modules/@storefront-ui/vue/scripts/)

Require stack:
- /Users/sam/dev/test-storefront-ui/.yarn/unplugged/@storefront-ui-vue-npm-0.10.71-d47225d01b/node_modules/@storefront-ui/vue/scripts/create-index-files.js
    at internalTools_makeError (/Users/sam/dev/test-storefront-ui/.pnp.js:7942:34)
    at resolveToUnqualified (/Users/sam/dev/test-storefront-ui/.pnp.js:8907:23)
    at resolveRequest (/Users/sam/dev/test-storefront-ui/.pnp.js:8999:29)
    at Object.resolveRequest (/Users/sam/dev/test-storefront-ui/.pnp.js:9077:26)
    at Function.external_module_.Module._resolveFilename (/Users/sam/dev/test-storefront-ui/.pnp.js:8175:34)
    at Function.external_module_.Module._load (/Users/sam/dev/test-storefront-ui/.pnp.js:8040:48)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/sam/dev/test-storefront-ui/.yarn/unplugged/@storefront-ui-vue-npm-0.10.71-d47225d01b/node_modules/@storefront-ui/vue/scripts/create-index-files.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)```

**Comment by AdamPawlinski** [comment]
I finally reproduce this error when changed the nodeLinker mode to pnp. Adding glob dependency helped to install storefront ui and run nuxt project, but when tried it on clear vue project or VSF Next other bugs appeared (not connected to storefront ui). One solution is to add `pnpMode: loose` in .yarnrc.yml file which is mixed mode node-modules with pnp. So I think this glob dependecy can be added, but can't solve all issues that can appear on yarn2 projects.
