### ISSUE TITLE
Nuxt build gives error

### ISSUE THREAD

**Issue by hahuaz** [vuestorefront/storefront-ui#1956]
**Describe the bug**
I am able to use storefront with nuxt in dev mode. But when I use build command I get error.

**How to reproduce**
1. Install the repo [nuxt-storefrontui-error](https://github.com/hahuaz/nuxt-storefrontui-error)
2. Run the below commands.
```
npm i
npm run build
```

**Expected behavior**
Succesfull nuxt build.

**Actual behavior**
Gives error:

```
ERROR in ./node_modules/@storefront-ui/vue/src/components/molecules/SfComponentSelect/SfComponentSelect.vue?vue&type=style&index=0&lang=scss& (./node_modules/@nuxt/postcss8/node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@storefront-ui/vue/src/components/molecules/SfComponentSelect/SfComponentSelect.vue?vue&type=style&index=0&lang=scss&)
Module build failed (from ./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js):
ParserError: Syntax Error at line: 1, column 98
    at C:\Users\hasan\Desktop\nuxt-storefrontui-error-main\nuxt-storefrontui-error-main\node_modules\@storefront-ui\vue\src\components\molecules\SfComponentSelect\SfComponentSelect.vue:1:1658
    at Parser.error (C:\Users\hasan\Desktop\nuxt-storefrontui-error-main\nuxt-storefrontui-error-main\node_modules\postcss-values-parser\lib\parser.js:127:11)
    at Parser.operator (C:\Users\hasan\Desktop\nuxt-storefrontui-error-main\nuxt-storefrontui-error-main\node_modules\postcss-values-parser\lib\parser.js:162:20)
    at Parser.parseTokens (C:\Users\hasan\Desktop\nuxt-storefrontui-error-main\nuxt-storefrontui-error-main\node_modules\postcss-values-parser\lib\parser.js:245:14)
    at Parser.loop (C:\Users\hasan\Desktop\nuxt-storefrontui-error-main\nuxt-storefrontui-error-main\node_modules\postcss-values-parser\lib\parser.js:132:12)
    at Parser.parse (C:\Users\hasan\Desktop\nuxt-storefrontui-error-main\nuxt-storefrontui-error-main\node_modules\postcss-values-parser\lib\parser.js:51:17)
    at parse (C:\Users\hasan\Desktop\nuxt-storefrontui-error-main\nuxt-storefrontui-error-main\node_modules\postcss-custom-properties\index.cjs.js:47:30)
    at C:\Users\hasan\Desktop\nuxt-storefrontui-error-main\nuxt-storefrontui-error-main\node_modules\postcss-custom-properties\index.cjs.js:333:24
    at C:\Users\hasan\Desktop\nuxt-storefrontui-error-main\nuxt-storefrontui-error-main\node_modules\postcss\lib\container.js:72:18
    at C:\Users\hasan\Desktop\nuxt-storefrontui-error-main\nuxt-storefrontui-error-main\node_modules\postcss\lib\container.js:55:18
    at Rule.each (C:\Users\hasan\Desktop\nuxt-storefrontui-error-main\nuxt-storefrontui-error-main\node_modules\postcss\lib\container.js:41:16)
    at Rule.walk (C:\Users\hasan\Desktop\nuxt-storefrontui-error-main\nuxt-storefrontui-error-main\node_modules\postcss\lib\container.js:52:17)
    at C:\Users\hasan\Desktop\nuxt-storefrontui-error-main\nuxt-storefrontui-error-main\node_modules\postcss\lib\container.js:60:24
    at Root.each (C:\Users\hasan\Desktop\nuxt-storefrontui-error-main\nuxt-storefrontui-error-main\node_modules\postcss\lib\container.js:41:16)
    at Root.walk (C:\Users\hasan\Desktop\nuxt-storefrontui-error-main\nuxt-storefrontui-error-main\node_modules\postcss\lib\container.js:52:17)
    at Root.walkDecls (C:\Users\hasan\Desktop\nuxt-storefrontui-error-main\nuxt-storefrontui-error-main\node_modules\postcss\lib\container.js:70:19)
    at transformProperties (C:\Users\hasan\Desktop\nuxt-storefrontui-error-main\nuxt-storefrontui-error-main\node_modules\postcss-custom-properties\index.cjs.js:330:8)
 @ ./node_modules/@storefront-ui/vue/src/components/molecules/SfComponentSelect/SfComponentSelect.vue?vue&type=style&index=0&lang=scss& (./node_modules/vue-style-loader??ref--7-oneOf-1-0!./node_modules/@nuxt/postcss8/node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@storefront-ui/vue/src/components/molecules/SfComponentSelect/SfComponentSelect.vue?vue&type=style&index=0&lang=scss&) 4:14-504
 @ ./node_modules/@storefront-ui/vue/src/components/molecules/SfComponentSelect/SfComponentSelect.vue?vue&type=style&index=0&lang=scss&
 @ ./node_modules/@storefront-ui/vue/src/components/molecules/SfComponentSelect/SfComponentSelect.vue
 @ ./node_modules/@storefront-ui/vue/index.js
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=script&lang=js&
 @ ./pages/index.vue?vue&type=script&lang=js&
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js

 FATAL  Nuxt build error                                                                                         17:32:30  

  at WebpackBundler.webpackCompile (node_modules\@nuxt\webpack\dist\webpack.js:2127:21)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async WebpackBundler.build (node_modules\@nuxt\webpack\dist\webpack.js:2076:5)
  at async Builder.build (node_modules\@nuxt\builder\dist\builder.js:327:5)
  at async Generator.initiate (node_modules\@nuxt\generator\dist\generator.js:110:7)
  at async Generator.generate (node_modules\@nuxt\generator\dist\generator.js:71:5)
  at async Object.run (node_modules\@nuxt\cli\dist\cli-build.js:106:7)
  at async NuxtCommand.run (node_modules\@nuxt\cli\dist\cli-index.js:413:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯
```

**Devices (please complete the following information):**
 - Device: [Desktop]
 - OS: [Windows 10]
 - Browser: [chrome]

**Comment by Baroshem** [comment]
Hi @hahuaz,

You said that you followed the steps from the video tutorial about adding Storefront UI to Nuxt project but there was no section about Axios nor TailwindCSS there. This is probably causing your errors (TailwindCSS configuration with Storefront UI). Please check #1807 for instructions on how to integrate TailwindCSS with SFUI.

**Comment by hahuaz** [comment]
It was due TailwindCSS integration. I have followed instructions and the build doesn't give error anymore. Thank you.
